INSERT INTO `tags` (`name`) VALUES
("Foodporn"),
("Yum"),
("Foodstagram"),
("Instafood"),
("Delicious"),
("Tasty"),
("Nom"),
("Foodie"),
("Hungry"),
("Dinner"),
("Lunch"),
("Breakfast"),
("Dessert"),
("Vegan"),
("Vegetarian"),
("Glutenfree"),
("Healthy"),
("Homemade"),
("Cooking"),
("Baking"),
("Grilling"),
("Bbq"),
("Restaurant"),
("Fastfood"),
("Streetfood"),
("Seafood"),
("Sushi"),
("Pizza"),
("Pasta"),
("Chinese"),
("Indian"),
("Mexican"),
("Italian"),
("French");

INSERT INTO `ingredients` (`name`, `color`)
VALUES 
("tomatoes", "ff0000"),
("carrots", "ffa500"),
("spinach", "00ff00"),
("blueberries", "0000ff"),
("strawberries", "ff00ff"),
("raspberries", "ff7700"),
("blackberries", "000000"),
("bananas", "ffff00"),
("avocados", "66ff99"),
("lemons", "ffff00"),
("limes", "00ff00"),
("cucumbers", "009933"),
("pumpkin", "ff9900"),
("ginger", "ff3300"),
("onions", "ff6600"),
("garlic", "999999"),
("chicken breast", "ffcc99"),
("ground beef", "ff0000"),
("salmon fillet", "ff6699"),
("shrimps", "ffcc99"),
("tofu", "cccccc"),
("lentils", "cc9966"),
("black beans", "333333"),
("kidney beans", "990000"),
("chickpeas", "663300"),
("quinoa", "99cc00"),
("brown rice", "663300"),
("peas", "009933"),
("corn", "ffcc00"),
("broccoli", "006600"),
("cauliflower", "ffffcc"),
("brussels sprouts", "996633"),
("potatoes", "ffcc99"),
("sweet potatoes", "ff6600"),
("yams", "ff3300"),
("apples", "ff0000"),
("oranges", "ffa500"),
("pears", "ffff00"),
("mangoes", "ffcc00"),
("pineapple", "ffff00"),
("cantaloupe", "ffcc66"),
("watermelon", "669900"),
("kiwi", "99cc00"),
("grapes", "663300"),
("plums", "990000"),
("figs", "663300"),
("dates", "cc9966");

INSERT INTO `measures` (`name`, `acronym`) VALUES
("teaspoon", "tsp"),
("tablespoon", "tbsp"),
("cup", "c"),
("pint", "pt"),
("quart", "qt"),
("gallon", "gal"),
("milliliter", "mL"),
("liter", "L"),
("milligram", "mg"),
("gram", "g"),
("kilogram", "kg"),
("ounce", "oz"),
("pound", "lb"),
("count", "cnt"),
("piece", "pc"),
("slice", "slc");

INSERT INTO `expressedin` (`ingredient`, `unit`) VALUES
('carrot', 'unit'),
('carrot', 'gram'),
('flour', 'gram'),
('flour', 'kilogram'),
('egg', 'unit'),
('mint', 'unit'),
('mint', 'gram'),
('oil', 'gram'),
('oil', 'litre'),
('oil', 'spoon'),
('salt', 'gram'),
('salt', 'spoon'),
('sugar', 'gram'),
('sugar', 'spoon'),
('water', 'gram'),
('water', 'litre'),
('rice', 'gram'),
('pepper', 'gram'),
('pepper', 'spoon'),
('rice', 'kilogram');